<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
row1 = int(input("Enter the number of rows of first matrix :"))      #for matrix 1 input
col1 = int(input("Enter the number of cols of first matrix : "))
matrix_1= []
for i in range (row1):
    mat1 =[]
    for j in range(col1):
        mat1.append(int(input("enter number for row  "+str(i+1))))
    matrix_1.append (mat1)
    
for m in (matrix_1):
    print(m)
    
row2 = int(input("Enter the number of rows of second  matrix :"))        # for matrix 2 input
col2 = int(input("Enter the number of cols of second matrix : "))
matrix_2= []
for i in range (row2):
    mat2 =[]
    for j in range(col2):
        mat2.append(int(input("enter number for row  "+str(i+1))))
    matrix_2.append (mat2)
    
for m in (matrix_2):
    print(m)

    
def matrix_mul(col1,row1,col2,row2,matrix_1,matrix_2):
    result=[[0 for j in range(col2)] for i in range (row1)]                      #reference taken from geekforgeeks
    
    if(row2==col1):
        for i in range(len(matrix_1)):
            for j in range(len(matrix_2[0])):
                result[i][j] = 0
                for k in range(len(matrix_2)):
                    result[i][j] = result[i][j] + matrix_1[i][k] * matrix_2 [k][j]
                    
        print_result(result)
    
    else:
        print("multiplication is not possbile")
    
        
def print_result(result):
    print("The result of matrix multiplication is :")
    for i in range(len(result)):
        for j in range(len(result[0])):
            print(result[i][j], end=" ")
        print("\n")
        
matrix_mul(col1,row1,col2,row2,matrix_1,matrix_2)                               # function call

Enter the number of rows of first matrix :2
Enter the number of cols of first matrix : 2
enter number for row  11
enter number for row  12
enter number for row  23
enter number for row  24
[1, 2]
[3, 4]
Enter the number of rows of second  matrix :2
Enter the number of cols of second matrix : 5
enter number for row  11
enter number for row  12
enter number for row  13
enter number for row  14
enter number for row  15
enter number for row  25
enter number for row  26
enter number for row  27
enter number for row  28
enter number for row  29
[1, 2, 3, 4, 5]
[5, 6, 7, 8, 9]
The result of matrix multiplication is :
11 14 17 20 23 

23 30 37 44 51 



<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [1]:
import random
import pandas as pd

def input_fun(length) :
    
    num_list = []
    for l in range(length):
        num = int(input("enter "+ str(l+1) +" number :"))
        num_list.append(num)
    return num_list

def pick_a_number_from_list(A,length):
    sum = 0
    for i in range (length):
        sum = sum+A[i]
    new_A = []
    for i in range(length):
        result = A[i] / sum
        new_A.append(result)
    series = pd.Series(new_A)                               #reference taken fromm stack overflow
    replaced_value = series.cumsum(skipna = False)
    
    probability = random.uniform(0.0, 1.0)                        # reference taken from pynative.com  
    
    for l in range(length):
        if probability < replaced_value[l] :
            return l
        elif probability >replaced_value[1] and probability < replaced_value[l+1]:
            return l+1
                                                    
def sampling_based_on_magnitued():
    length  = int(input(" How many Number you want to enter ??"))
    num_list = input_fun(length)
    #A = [0,5,27,6,13,28,100,45,10,79]   
    #length_of_A = len(A)
    for i in range(1,100):
        number = pick_a_number_from_list(num_list,length)
        print(num_list[number])
        
sampling_based_on_magnitued() 

 How many Number you want to enter ??10
enter 1 number :0
enter 2 number :5
enter 3 number :27
enter 4 number :6
enter 5 number :13
enter 6 number :28
enter 7 number :100
enter 8 number :45
enter 9 number :10
enter 10 number :79
100
13
27
79
45
100
100
79
100
10
79
45
28
45
100
79
27
27
100
79
45
79
79
45
100
79
79
5
79
28
5
100
27
28
79
79
100
100
100
27
79
100
79
100
100
100
13
79
100
100
45
27
100
79
79
45
45
45
10
45
79
100
79
79
100
79
100
79
100
100
100
79
79
45
27
27
100
100
79
100
6
100
100
100
45
100
45
79
79
100
79
79
79
79
79
100
100
100
100


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [18]:
import re

#user_str = str(input("Please enter your string"))
def replace_digits(user_str):
    #p = re.compile('\d')
    digit = re.findall(r'[0-9]', user_str) 
    return digit

def print_func(digit):
    for a in range(len(digit)):
        print("#", end="")

#{  main calling        
user_str1 = "234"
user_str2 = "a2b3c4 "
user_str3 = "abc"
user_str4 = "#2a$#b%c%561#"

dig1 = replace_digits(user_str1) 
print(str(user_str1)+" : " , end="") 
print_func(dig1)

dig2 = replace_digits(user_str2) 
print("\n"+ str(user_str2)+" : " , end="") 
print_func(dig2)

dig3 = replace_digits(user_str3) 
print("\n"+str(user_str3)+" : " , end="") 
print_func(dig3)

dig4 = replace_digits(user_str4) 
print("\n" +str(user_str4)+" : " , end="") 
print_func(dig4)
#}

234 : ###
a2b3c4  : ###
abc : 
#2a$#b%c%561# : ####

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [2]:
from collections import Counter
import numpy as np

def input_data():
    Students = []
    Marks = []
    n = int(input("Enter the total number of Students : "))
    for i in range(0,n):
        i = str(input("Enter the name of student " +str(i+1)+" : "))
        Students.append(i)

    for j in range (0,n):
        j = int(input("Enter the Mark of student  " +str(j+1)+" :"))
        Marks.append(j)
   
    per_25 = np.percentile(Marks, 25)
    per_75 = np.percentile(Marks, 75)
    
    return Students,Marks,per_25,per_75

def Convert_to_dict (Students,Marks):
    new_students_marks = {}                       # converting two list into one dictionary 
    for key in Students:                          # reference taken from geekfromgeeks
        for value in Marks: 
            new_students_marks[key] = value 
            Marks.remove(value) 
            break
    return new_students_marks

def Top_Rank (new_students_marks):
    desc_sorted_dict = sorted(new_students_marks .items(), key=lambda x: x[1] , reverse=True)  
    k1= Counter(desc_sorted_dict)
    top_rank = k1.most_common(5) 
    print("Name of Students who got TOP 5 ranks :")
    for key,value in top_rank: 
        print(key)

def Least_Rank(new_students_marks):
    asc_sorted_dict = sorted(new_students_marks .items(), key=lambda x: x[1])
    #print(asc_sorted_dict)
    k2 = Counter(asc_sorted_dict)
    least_rank = k2.most_common(5) 

    print("\n Name of Students who got LEAST 5 ranks :")
    for key,value in least_rank: 
        print(key) 
    return asc_sorted_dict
        
def Percentile_Rank(asc_sorted_dict,per_25,per_75):    
    print("\n The students Who got marks between >25th percentile :"+str(per_25) +"<75th percentile :"+ str(per_75))
    print(*(" {}, {}\n ".format(students,marks) for (students, marks) in asc_sorted_dict if (marks >per_25 and marks < per_75)))
       
# functions calling     
Students,Marks,per_25,per_75 = input_data()
new_stud_marks = Convert_to_dict (Students,Marks)
#print(new_stud_marks)
Top_Rank (new_stud_marks)
asc_sorted_dict = Least_Rank(new_stud_marks)
Percentile_Rank(asc_sorted_dict,per_25,per_75)      

Enter the total number of Students : 10
Enter the name of student 1 : student1
Enter the name of student 2 : student2
Enter the name of student 3 : student3
Enter the name of student 4 : student4
Enter the name of student 5 : student5
Enter the name of student 6 : student6
Enter the name of student 7 : student7
Enter the name of student 8 : student8
Enter the name of student 9 : student9
Enter the name of student 10 : student10
Enter the Mark of student  1 :45
Enter the Mark of student  2 :78
Enter the Mark of student  3 :12
Enter the Mark of student  4 :14
Enter the Mark of student  5 :48
Enter the Mark of student  6 :43
Enter the Mark of student  7 :47
Enter the Mark of student  8 :98
Enter the Mark of student  9 :35
Enter the Mark of student  10 :80
Name of Students who got TOP 5 ranks :
('student8', 98)
('student10', 80)
('student2', 78)
('student5', 48)
('student7', 47)

 Name of Students who got LEAST 5 ranks :
('student3', 12)
('student4', 14)
('student9', 35)
('student6', 43)
(

<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [19]:
import math

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

print("Cosine Distance between the two points :")
new_list = sorted(S, key= lambda x: math.acos((float(x[0]* P[0] + x[1] * P[1])) \
            / ((float(math.sqrt (x[0]* x[0] +x[1] * x[1])) * (math.sqrt (P[0]* P[0] +P[1] * P[1]))))) )  #geeksfromgeeks

print(new_list)
print("The closest points are :")
#new_list.sort()
print(new_list[:5])

Cosine Distance between the two points :
[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1), (3, 4), (1, 2), (0, 6), (-1, 1)]
The closest points are :
[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [1]:
import re
import math

Red= [[1,1],[2,1],[4,2],[2,4],[-1,4]]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

def line_coef():
    Line =[]
    for line in Lines:
        temp=[]
        a, b, c = [float(coef.strip()) for coef in re.split('x|y', line)]
        #print(a, b, c)
        temp.append(a)
        temp.append(b)
        temp.append(c)
        Line.append(temp)
    return Line

def point_distance_function(Red,Line) :
    distance_list = []
    dis =0.0
    for l in range(len(Line)):
        r_dis = []
        for r in range (len(Red)) :
            #distance[l][r] = 0
            dis = (Line[l][0] * Red[r][0] + Line[l][1] * Red[r][1] + Line[l][2] ) \
            / (math.sqrt(Line[l][0]*Line[l][0] + Line[l][1]*Line[l][1]))
            #print("dis  "+str(dis) +" for   " +str(Red[r]))
            
            if dis >= 0.0 :
                r_dis.append(True)
            elif dis < 0.0:
                r_dis.append (False)
            else :
                pass
            
        distance_list.append(r_dis)
        #print(distance_list)
    return distance_list

def main_flag_list (distance_list):
    main_flag_list = []
    for r in range (len(distance_list)):
        flag_list = []
        al = all(distance_list[r])
        #print (al)
        flag_list.append(al)
        #print(flag_list)
        main_flag_list.append(flag_list)
    return main_flag_list
   
def yes_or_no (Line,list1,list2):
    for l in range(len(Line)):
        if ((list1[l]== [True]) and (list2[l]== [False])) :
            print("yes")
        elif ((list1[l]== [False]) and (list2[l]== [True])) :
            print("yes")
        else:
            print("No")                   
        

#  functions calling  :

Line = line_coef()
r_distance_list = point_distance_function(Red,Line)
red_flag_list = main_flag_list (r_distance_list)
#print(red_flag_list)

b_distance_list = point_distance_function(Blue,Line)
blue_flag_list = main_flag_list (b_distance_list)
#print(blue_flag_list)

yes_or_no (Line,red_flag_list,blue_flag_list)



yes
No
No
yes


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [6]:
def curve_smoothing (input_string):
    #string_split = []
    string_split = input_string.split(",")
    ser_number = [i for i, value in enumerate(string_split) if value != '_']           # reference taken from stack overflow
    
    if ser_number[0] != 0:
        ser_number = [-1] + ser_number
    
    if ser_number[-1] != len(string_split)-1:
        ser_number = ser_number + [-1]    
    
    for (start, end) in zip(ser_number[:-1], ser_number[1:]): 
        if start == -1:
            value = float(string_split[end])/(end+1)
            for i in range(start+1,end+1):
                string_split[i] = int( value) 
        elif end == -1:
            value = float(string_split[start])/(len(string_split)-start)
            for i in range(start, len(string_split)):
                string_split[i] = int( value ) 
        else:
            value = (int(string_split[start])+int(string_split[end]))/(end-start+1)
            for i in range(start,end+1):
                string_split[i] = int( value )         
    return string_split
    
input_string_1 = "_,_,_,24 "
input_string_2 = "40,_,_,_,60"
input_string_3 = "80,_,_,_,_"
input_string_4 = "_,_,30,_,_,_,50,_,_"

split1 = curve_smoothing (input_string_1)
print(input_string_1 + " :  " +str(split1))
split2 = curve_smoothing (input_string_2)
print(input_string_2 + " :  " +str(split2))
split3 = curve_smoothing (input_string_3)
print(input_string_3 + " :  " +str(split3))
split4 = curve_smoothing (input_string_4)
print(input_string_4 + " :  " +str(split4))


_,_,_,24  :  [6, 6, 6, 6]
40,_,_,_,60 :  [20, 20, 20, 20, 20]
80,_,_,_,_ :  [16, 16, 16, 16, 16]
_,_,30,_,_,_,50,_,_ :  [10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [20]:
A = [["F1","S1"],["F2","S2"],["F3","S3"],["F1","S2"],["F2","S3"],["F3","S2"],["F2","S1"],["F4","S1"],["F4","S3"],["F5","S1"]]

dict_of_F = { 'F1S1':0, 'F2S1':0, 'F3S1':0, 'F4S1':0,'F5S1':0,'F1S2':0,'F2S2':0,'F3S2':0,'F4S2':0,'F5S2':0,'F1S3':0,
                'F2S3':0,'F3S3':0,'F4S3':0,'F5S3':0 }

dict_of_S = { 'S1': 0, 'S2': 0, 'S3': 0 }

def compute_conditional_probabilites(A):
    for i in range(len(A)):
        k = A[i][0] + A[i][1]
        dict_of_F[k] += 1
        dict_of_S[A[i][1]] += 1
            
#main functions calling :
#{
compute_conditional_probabilites(A)

print("Probability of P(F=F1|S==S1) :" + str(dict_of_F['F1S1']) + "/" + str( dict_of_S['S1']) + \
     "  P(F=F1|S==S2) :" +  str(dict_of_F['F1S2']) + "/" + str(dict_of_S['S2']) + \
      "  P(F=F1|S==S3) :" + str(dict_of_F['F1S3'])  + "/" + str(dict_of_S['S3']))

print("Probability of P(F=F2|S==S1) :" + str(dict_of_F['F2S1']) + "/" + str( dict_of_S['S1']) + \
     "  P(F=F2|S==S2) :" +  str(dict_of_F['F2S2']) + "/" + str(dict_of_S['S2']) + \
      "  P(F=F2|S==S3) :" + str(dict_of_F['F2S3'])  + "/" + str(dict_of_S['S3']))

print("Probability of P(F=F3|S==S1) :" + str(dict_of_F['F3S1']) + "/" + str( dict_of_S['S1']) + \
     "  P(F=F3|S==S2) :" +  str(dict_of_F['F3S2']) + "/" + str(dict_of_S['S2']) + \
      "  P(F=F3|S==S3) :" + str(dict_of_F['F3S3'])  + "/" + str(dict_of_S['S3']))

print("Probability of P(F=F4|S==S1) :" + str(dict_of_F['F4S1']) + "/" + str( dict_of_S['S1']) + \
     "  P(F=F4|S==S2) :" +  str(dict_of_F['F4S2']) + "/" + str(dict_of_S['S2']) + \
      "  P(F=F4|S==S3) :" + str(dict_of_F['F4S3'])  + "/" + str(dict_of_S['S3']))

print("Probability of P(F=F5|S==S1) :" + str(dict_of_F['F5S1']) + "/" + str( dict_of_S['S1']) + \
     "  P(F=F5|S==S2) :" +  str(dict_of_F['F5S2']) + "/" + str(dict_of_S['S2']) + \
      "  P(F=F5|S==S3) :" + str(dict_of_F['F5S3'])  + "/" + str(dict_of_S['S3']))
#}
     
   
  

Probability of P(F=F1|S==S1) :1/4  P(F=F1|S==S2) :1/3  P(F=F1|S==S3) :0/3
Probability of P(F=F2|S==S1) :1/4  P(F=F2|S==S2) :1/3  P(F=F2|S==S3) :1/3
Probability of P(F=F3|S==S1) :0/4  P(F=F3|S==S2) :1/3  P(F=F3|S==S3) :1/3
Probability of P(F=F4|S==S1) :1/4  P(F=F4|S==S2) :0/3  P(F=F4|S==S3) :1/3
Probability of P(F=F5|S==S1) :1/4  P(F=F5|S==S2) :0/3  P(F=F5|S==S3) :0/3


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [1]:
def string_features(str1, str2):
    split_1 = str1.split(" ")
    #print(split_1)
    split_2 =  str2.split(" ")
    #print(split_2)
    count = 0
    for s1 in range(len(split_1)):
        for s2 in range(len(split_2)):
            if split_1[s1] == split_2[s2]:
                count +=1
                #print(split_1[s1])          
    return count,split_1,split_2


str1 = input("Enter the first string")
str2 = input("Enter the second string ")
count,split_1,split_2 = string_features (str1,str2)
print("Number of common words between Str1, Str2 :",count)

set_1_uncom = [ x for x in split_1 if x not in split_2 ]
print(set_1_uncom)

set_2_uncom = [ x for x in split_2 if x not in split_1 ]
print(set_2_uncom)

Enter the first stringthe first column F will contain only 5 unique values
Enter the second string the second column S will contain only 3 unique values
Number of common words between Str1, Str2 : 7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [3]:
import math
matrix_list = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

def compute_log_loss(matrix_list):
    loss = 0
    for m in range(len(matrix_list)):
        loss = loss + ((matrix_list[m][0] * math.log (matrix_list[m][1],10)) \
                       + ((1- matrix_list[m][0]) * math.log((1 - matrix_list[m][1]),10)))  #formula math.log(a,base) from geeks
        #print(loss)
    loss1 = loss * (-1 / len(matrix_list)) 
    return loss1

loss = compute_log_loss(matrix_list)
print("loss :",loss)

loss : 0.42430993457031635
