# Assignment

<font face='georgia'>
    
   <h4><strong>What does tf-idf mean?</strong></h4>

   <p>    
Tf-idf stands for <em>term frequency-inverse document frequency</em>, and the tf-idf weight is a weight often used in information retrieval and text mining. This weight is a statistical measure used to evaluate how important a word is to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus. Variations of the tf-idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query.
</p>
    
   <p>
One of the simplest ranking functions is computed by summing the tf-idf for each query term; many more sophisticated ranking functions are variants of this simple model.
</p>
    
   <p>
Tf-idf can be successfully used for stop-words filtering in various subject fields including text summarization and classification.
</p>
    
</font>

<font face='georgia'>
    <h4><strong>How to Compute:</strong></h4>

Typically, the tf-idf weight is composed by two terms: the first computes the normalized Term Frequency (TF), aka. the number of times a word appears in a document, divided by the total number of words in that document; the second term is the Inverse Document Frequency (IDF), computed as the logarithm of the number of the documents in the corpus divided by the number of documents where the specific term appears.

 <ul>
    <li>
<strong>TF:</strong> Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization: <br>

$TF(t) = \frac{\text{Number of times term t appears in a document}}{\text{Total number of terms in the document}}.$
</li>
<li>
<strong>IDF:</strong> Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following: <br>

$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}}.$
for numerical stabiltiy we will be changing this formula little bit
$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}+1}.$
</li>
</ul>

<br>
<h4><strong>Example</strong></h4>
<p>

Consider a document containing 100 words wherein the word cat appears 3 times. The term frequency (i.e., tf) for cat is then (3 / 100) = 0.03. Now, assume we have 10 million documents and the word cat appears in one thousand of these. Then, the inverse document frequency (i.e., idf) is calculated as log(10,000,000 / 1,000) = 4. Thus, the Tf-idf weight is the product of these quantities: 0.03 * 4 = 0.12.
</p>
</font>

## Task-1

<font face='georgia'>
    <h4><strong>1. Build a TFIDF Vectorizer & compare its results with Sklearn:</strong></h4>

<ul>
    <li> As a part of this task you will be implementing TFIDF vectorizer on a collection of text documents.</li>
    <br>
    <li> You should compare the results of your own implementation of TFIDF vectorizer with that of sklearns implemenation TFIDF vectorizer.</li>
    <br>
    <li> Sklearn does few more tweaks in the implementation of its version of TFIDF vectorizer, so to replicate the exact results you would need to add following things to your custom implementation of tfidf vectorizer:
       <ol>
        <li> Sklearn has its vocabulary generated from idf sroted in alphabetical order</li>
        <li> Sklearn formula of idf is different from the standard textbook formula. Here the constant <strong>"1"</strong> is added to the numerator and denominator of the idf as if an extra document was seen containing every term in the collection exactly once, which prevents zero divisions.
            
 $IDF(t) = 1+\log_{e}\frac{1\text{ }+\text{ Total  number of documents in collection}} {1+\text{Number of documents with term t in it}}.$
        </li>
        <li> Sklearn applies L2-normalization on its output matrix.</li>
        <li> The final output of sklearn tfidf vectorizer is a sparse matrix.</li>
    </ol>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer.</li>
        <li> Print out the alphabetically sorted voacb after you fit your data and check if its the same as that of the feature names from sklearn tfidf vectorizer. </li>
        <li> Print out the idf values from your implementation and check if its the same as that of sklearns tfidf vectorizer idf values. </li>
        <li> Once you get your voacb and idf values to be same as that of sklearns implementation of tfidf vectorizer, proceed to the below steps. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> After completing the above steps, print the output of your custom implementation and compare it with sklearns implementation of tfidf vectorizer.</li>
        <li> To check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it.</li>
        </ol>
    </li>
    <br>
   </ul>

  <p> <font color="#e60000"><strong>Note-1: </strong></font> All the necessary outputs of sklearns tfidf vectorizer have been provided as reference in this notebook, you can compare your outputs as mentioned in the above steps, with these outputs.<br>
   <font color="#e60000"><strong>Note-2: </strong></font> The output of your custom implementation and that of sklearns implementation would match only with the collection of document strings provided to you as reference in this notebook. It would not match for strings that contain capital letters or punctuations, etc, because sklearn version of tfidf vectorizer deals with such strings in a different way. To know further details about how sklearn tfidf vectorizer works with such string, you can always refer to its official documentation.<br>
   <font color="#e60000"><strong>Note-3: </strong></font> During this task, it would be helpful for you to debug the code you write with print statements wherever necessary. But when you are finally submitting the assignment, make sure your code is readable and try not to print things which are not part of this task.
    </p>

### Corpus

In [1]:
## SkLearn# Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

### SkLearn Implementation

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [3]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [4]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)

[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [5]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(4, 9)

In [6]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output[0])

  (0, 8)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045


In [7]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


### MY custom implementation

In [8]:
from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import os
import re

In [9]:
# Preprocessing on the given daaset

corpus = [
     "this is the first document",
     "this document is the second document",
     "and this is the third one",
     "is this the first document",
]

document = list()
for line in corpus :
     for l in re.split(r"\.\s|\?\s|\!\s|\n",line):
            if l:
                document.append(l)
#print(document)

def lower_case(doc):
    doc  = np.char.lower(doc)
    return doc

def punctionation(doc):
    symbols = "!\"#$%&()*+-./:;<=>?@[\]^_`{|}~\n"
    for i in symbols:
        doc = np.char.replace(doc, i, '')
    return doc

def apostrophe (doc):
    doc = np.char.replace(doc, "'", "") 
    return doc

# preprocessing :
document = lower_case(document)
document = punctionation(document)
document = apostrophe(document)
#print(document)

In [10]:
# calulation for BOW for each sentences from final document
BOW_list = []
for r in range (len(document)) :
    BOW = document[r].split()
    BOW_list.append(BOW)
 
BOW = []
for r in range(len(BOW_list)):
    l =len( BOW_list[r])
    BOW.append(l)
#print(BOW)

In [11]:
# fit function for TF-IDF to find unique words

def fit(dataset) :
    unique_words = set()
    
    if isinstance(dataset,(list,)):
        for row in dataset :
            for word in row.split(" "):
                if len(word)< 2 :
                    continue
                unique_words.add(word)
        unique_words = sorted(list(unique_words))
        vocab_list = [j for i,j in enumerate (unique_words)]                #vocab = list
        vocab_dict ={ j:i for i , j in enumerate (unique_words) }          #vocab = dictionray
        return vocab_list,vocab_dict
        
    else:
        print("please plass the proper list of sentence")
                    
vocab_list, vocab_dict = fit(corpus)
print(vocab_list)

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [12]:
# transform function for TF-IDF

def transform(dataset,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):
        for idx, row in enumerate(tqdm(dataset)): 
            
            word_freq = dict(Counter(row.split()))
            
            for word, freq in word_freq.items():                 
                if len(word) < 2:
                    continue
                
                col_index = vocab.get(word, -1) 
                
                if col_index !=-1:
                    
                    rows.append(idx)
                    
                    columns.append(col_index)
                    
                    values.append(freq)
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))
    else:
        print("you need to pass list of strings")
        
        
mat = transform(corpus,vocab_dict).toarray()
print(mat)

# conversion of mat matrix into dictionary 
dictionary = [dict(zip(vocab_dict, values)) for values in mat[0:]]
#print(dictionary)

100%|██████████| 4/4 [00:00<?, ?it/s]


[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [13]:
#recode 
#calculation of word frequency of each unique word
def cal_document_frequency(bow, vocab):
    word_list = []
    for v in range(len(vocab)) :
        count = 0
        for d in range(len(bow)):
            if vocab[v] in bow[d]:
                count = count+1
        word_list.append(count)
    return word_list       
        
DF_list  = cal_document_frequency(BOW_list, vocab_list)
DF_dict = {vocab_list[i]: DF_list[i] for i in range(len(vocab_list))} 
print(DF_dict)

{'and': 1, 'document': 3, 'first': 2, 'is': 4, 'one': 1, 'second': 1, 'the': 4, 'third': 1, 'this': 4}


In [14]:
#calculation of term frquency(TF) for each sentence:
tf_list = []
for r in range (len(mat)):
    tf = mat[r]/BOW[r]
    tf_list.append(tf)
#print(tf_list)
# conversion of tf matrix into dictionary
tf_dict =[ dict(zip(vocab_dict, values)) for values in tf_list[0:]]
print(len(tf_dict))

4


In [15]:
#calculate Inverse document frequency (IDF)
def calculate_IDF(document, DF_dict):
    IDF_dict = {}
    N = len(document)
    
    IDF_dict = dict.fromkeys(IDF_dict,0)
    for word, val in DF_dict.items():
        IDF_dict[word] =  1+ (math.log((1+N) / (1+float(val))))
    
    return IDF_dict

IDF_val = calculate_IDF(document, DF_dict)           # dictionary of idf value
IDF_val_sorted = sorted(IDF_val.items())
print(IDF_val_sorted)

[('and', 1.916290731874155), ('document', 1.2231435513142097), ('first', 1.5108256237659907), ('is', 1.0), ('one', 1.916290731874155), ('second', 1.916290731874155), ('the', 1.0), ('third', 1.916290731874155), ('this', 1.0)]


Observation : compared the result of IDF value with TfidfVectorizer for IDF values 
              each of vaocb unique word got the exact value for idf

In [16]:
# calculation of tf-idf values

def calculate_TF_IDF(tf,idf) :
    tfidf_list = []
    for word,val in tf.items():
        tfidf = val * idf[word]
        tfidf_list.append(tfidf)
    return tfidf_list

TF_IDF_list = []
for r in range(len(tf_dict)):
    row = calculate_TF_IDF(tf_dict[r], IDF_val)
    TF_IDF_list.append(row)
#print(TF_IDF_list)

In [17]:
#conversion into matrix array
matrix_tfidf = np.asarray(TF_IDF_list)
#print(matrix_tfidf)

In [18]:
#L2 Normalization
t = normalize(matrix_tfidf, norm='l2', axis=1, copy=True, return_norm=False)
#print(t)

In [19]:
print(t.shape)

(4, 9)


In [20]:
# Sparse Matrix representation
Sparse_matrix = csr_matrix(t[0])
print(Sparse_matrix)

  (0, 1)	0.4697913855799205
  (0, 2)	0.580285823684436
  (0, 3)	0.3840852409148149
  (0, 6)	0.3840852409148149
  (0, 8)	0.3840852409148149


In [21]:
# convertion of the sparse output matrix to dense matrix
print(np.asarray(t[0]))

[0.         0.46979139 0.58028582 0.38408524 0.         0.
 0.38408524 0.         0.38408524]


## Task-2

<font face='georgia'>
    <h4><strong>2. Implement max features functionality:</strong></h4>

<ul>
    <li> As a part of this task you have to modify your fit and transform functions so that your vocab will contain only 50 terms with top idf scores.</li>
    <br>
    <li>This task is similar to your previous task, just that here your vocabulary is limited to only top 50 features names based on their idf values. Basically your output will have exactly 50 columns and the number of rows will depend on the number of documents you have in your corpus.</li>
    <br>
    <li>Here you will be give a pickle file, with file name <strong>cleaned_strings</strong>. You would have to load the corpus from this file and use it as input to your tfidf vectorizer.</li>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer, just like in the previous task. Additionally, here you have to limit the number of features generated to 50 as described above.</li>
        <li> Now sort your vocab based in descending order of idf values and print out the words in the sorted voacb after you fit your data. Here you should be getting only 50 terms in your vocab. And make sure to print idf values for each term in your vocab. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> Now check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it. And this dense matrix should contain 1 row and 50 columns. </li>
        </ol>
    </li>
    <br>
   </ul>

## SKlearn Implementation for cleaned_strings File

In [26]:
import pickle
with open('cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)
# printing the length of the corpus loaded

#corpus_1=corpus[0:10]
print("Number of documents in corpus = ",len(corpus))

Number of documents in corpus =  746


In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer().fit(corpus)
features=vectorizer.get_feature_names()

In [28]:
vectorizer.idf_

array([6.922918  , 6.922918  , 6.22977082, ..., 6.922918  , 6.5174529 ,
       6.922918  ])

In [29]:
sorted_idf = sorted(vectorizer.idf_ , reverse = True)
top_no_features = 50
indices = np.argsort(sorted_idf)[::-1]
top_features = [features[i] for i in indices[:top_no_features]]
print (top_features)

['leading', 'flaw', 'flashbacks', 'flaming', 'flakes', 'flag', 'five', 'fit', 'fisted', 'fishnet', 'fish', 'first', 'fire', 'finished', 'fingernails', 'finest', 'fine', 'finds', 'find', 'financial', 'finally', 'flat', 'flawed', 'glad', 'flaws', 'ford', 'forces', 'forced', 'force', 'football', 'footage', 'foolish', 'follows', 'following', 'follow', 'fodder', 'focus', 'flynn', 'flying', 'flowed', 'florida', 'flicks', 'flick', 'fleshed', 'finale', 'final', 'films', 'filmography', 'fear', 'favourite']


In [57]:
new_vocab = TfidfVectorizer().fit(top_features)
sparse = new_vocab.transform(corpus)
new_vocab.idf_

array([4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845,
       4.23867845, 4.23867845, 4.23867845, 4.23867845, 4.23867845])

In [31]:
sparse.shape

(746, 50)

In [32]:
print(sparse[1])

  (0, 25)	1.0


In [33]:
print(sparse[1].toarray())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]


### My implementation of task 2

In [34]:
# calulation for BOW for each sentences from final document
final_document = corpus
BOW_list = []
for r in range (len(final_document)) :
    BOW = final_document[r].split()
    BOW_list.append(BOW)
    
BOW = []
for r in range(len(BOW_list)):
    l =len( BOW_list[r])
    BOW.append(l)
print(len(BOW))

746


In [35]:
# fit function for TF-IDF to find the vocabulary
from sklearn.feature_extraction.text import TfidfVectorizer
def fit(dataset) :
    unique_words = set()
    
    if isinstance(dataset,(list,)):
        for row in dataset :
            for word in row.split(" "):
                if len(word)< 2 :
                    continue
                else:
                    unique_words.add(word)
        unique_words = sorted(list(unique_words))
        vocab_list = [j for i,j in enumerate (unique_words)]                #vocab = list
        vocab_dict ={ j:i for i , j in enumerate (unique_words) }          #vocab = dictionray
        return vocab_list,vocab_dict
        
    else:
        print("please plass the proper list of sentence")
                    
vocab_list, vocab_dict = fit(corpus)
print(len(vocab_list))

2886


In [36]:
# transform function for TF-IDF

def transform(dataset,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):
        for idx, row in enumerate(tqdm(dataset)): 
            word_freq = dict(Counter(row.split()))
            for word, freq in word_freq.items():                 
                if len(word) < 2:
                    continue
                col_index = vocab.get(word, -1) 
                if col_index !=-1:
                    rows.append(idx)
                    columns.append(col_index)
                    values.append(freq)
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))
    else:
        print("you need to pass list of strings")
        
        
mat = transform(corpus,vocab_dict).toarray()
print(mat)

100%|██████████| 746/746 [00:00<00:00, 61323.12it/s]


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [37]:
#calculation of word frequency of each unique word
def cal_document_frequency(bow, vocab):
    word_list = []
    for v in range(len(vocab)) :
        count = 0
        for d in range(len(bow)):
            if vocab[v] in bow[d]:
                count = count+1
            
        word_list.append(count)
    return word_list       
        
DF_list  = cal_document_frequency(BOW_list, vocab_list)
DF_dict = {vocab_list[i]: DF_list[i] for i in range(len(vocab_list))} 
#print(DF_dict)

In [38]:
# calculation of term frquency(TF) for each sentence:
tf_list = []
for r in range (len(mat)):
    tf = mat[r]/BOW[r]
    tf_list.append(tf)
# conversion of tf matrix into dictionary
tf_dict =[ dict(zip(vocab_list, values)) for values in tf_list[0:]]
print(len(tf_dict))

746


In [39]:
#calculate Inverse document frequency (IDF)
def calculate_IDF(document, DF):
    IDF_dict = {}
    N = len(document)
    IDF_dict = dict.fromkeys(IDF_dict,0)
    for word, val in DF.items():
        IDF_dict[word] = 1+(math.log((1+N) / (1+float(val))))
    return IDF_dict

IDF_val = calculate_IDF(final_document, DF_dict)                                           # dictionary of idf value
IDF_val_sorted = sorted(IDF_val.values(),reverse = True)

In [40]:
indices = np.argsort(IDF_val_sorted)[::-1]
top_features_50 = [vocab_list[i] for i in indices[:top_no_features]]
print (top_features_50)

['leading', 'flaw', 'flashbacks', 'flaming', 'flakes', 'flag', 'five', 'fit', 'fisted', 'fishnet', 'fish', 'first', 'fire', 'finished', 'fingernails', 'finest', 'fine', 'finds', 'find', 'financial', 'finally', 'flat', 'flawed', 'glad', 'flaws', 'ford', 'forces', 'forced', 'force', 'football', 'footage', 'foolish', 'follows', 'following', 'follow', 'fodder', 'focus', 'flynn', 'flying', 'flowed', 'florida', 'flicks', 'flick', 'fleshed', 'finale', 'final', 'films', 'filmography', 'fear', 'favourite']


Observaion : Compared my implemneted top 50 features with TFIDF vectorizer feaures. They are exactly equal.

In [42]:
new_vocab_list , new_vocab_dict = fit(top_features_50)
len(new_vocab_list)

50

In [43]:
mat_50 = transform(corpus,new_vocab_dict).toarray()
print(mat_50)

100%|██████████| 746/746 [00:00<00:00, 84806.91it/s]


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [44]:
DF_list_50  = cal_document_frequency(BOW_list, new_vocab_list)
DF_dict_50 = {new_vocab_list[i]: DF_list_50[i] for i in range(len(new_vocab_list))} 

In [46]:
# calculation of term frquency(TF) for each sentence:
tf_list_50 = []
for r in range (len(mat)):
    tf = mat_50[r]/BOW[r]
    tf_list_50.append(tf)

tf_dict_50 =[ dict(zip(new_vocab_list, values)) for values in tf_list_50[0:]]

In [61]:
#calculate Inverse document frequency (IDF)
IDF_val_50 = calculate_IDF(new_vocab_list, DF_dict_50)                                           # dictionary of idf value
IDF_val_sorted = sorted(IDF_val_50.values(),reverse = True)
print(IDF_val_50)

{'favourite': 3.545531271604435, 'fear': 3.545531271604435, 'filmography': 4.238678452164381, 'films': 1.9873866535578852, 'final': 3.545531271604435, 'finale': 4.238678452164381, 'finally': 3.545531271604435, 'financial': 4.238678452164381, 'find': 2.5339303599259555, 'finds': 4.238678452164381, 'fine': 3.1400661634962708, 'finest': 4.238678452164381, 'fingernails': 4.238678452164381, 'finished': 4.238678452164381, 'fire': 4.238678452164381, 'first': 2.5339303599259555, 'fish': 4.238678452164381, 'fishnet': 4.238678452164381, 'fisted': 4.238678452164381, 'fit': 4.238678452164381, 'five': 3.833213344056216, 'flag': 4.238678452164381, 'flakes': 4.238678452164381, 'flaming': 4.238678452164381, 'flashbacks': 4.238678452164381, 'flat': 3.833213344056216, 'flaw': 4.238678452164381, 'flawed': 3.833213344056216, 'flaws': 3.833213344056216, 'fleshed': 4.238678452164381, 'flick': 3.1400661634962708, 'flicks': 4.238678452164381, 'florida': 4.238678452164381, 'flowed': 4.238678452164381, 'flying'

In [62]:
# calculation of tf-idf values
def calculate_TF_IDF(tf,idf) :
    tfidf_list = []
    for word,val in tf.items():
        if word in idf:
            tfidf = val * idf[word]
        else:
            tfidf = 0.0
            
        tfidf_list.append(tfidf)
    return tfidf_list

TF_IDF_list_50 = []
for r in range(len(tf_dict_50)):
    row = calculate_TF_IDF(tf_dict_50[r], IDF_val_50)
    TF_IDF_list_50.append(row)

In [63]:
#conversion into matrix array
matrix_tfidf_50 = np.asarray(TF_IDF_list_50)
#L2 Normalization
t_50 = normalize(matrix_tfidf_50, norm='l2', axis=1, copy=True, return_norm=False)
print(t_50)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [64]:
# Sparse Matrix representation
Sparse_matrix = csr_matrix(t_50)
print(Sparse_matrix[1])

  (0, 25)	1.0


In [65]:
# convertion of the sparse output matrix to dense matrix
print(np.asarray(t_50[1]))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


Observation : compared the values of sparse matrix of bothe the two implementation. The values are exactly same.